# Generated by Django 5.0 on 2024-01-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_category_photo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='1', max_length=20)),
            ],
        ),
    ]
